version: "3.9"

services: 
  social_api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    container_name: api
    volumes: 
      - /home/app/node_modules
      - ./server:/home/app
    # ports: 
    #   - 5000:5000
    depends_on:
      - mongodb
    environment: 
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb
      CHOKIDAR_USEPOLLING: "true"
    networks: 
      - api
      
  mongodb:
      image: mongo
      restart: always
      ports: 
        - 27017:27017
      environment: 
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      volumes: 
        - /mongodb-data:/data/db
      networks: 
        - api

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on: 
      - mongodb
      - social_api
    ports: 
      - 8000:80
    networks: 
      - api

networks: 
  api:
    driver: bridge

volumes: 
  mongodb-data:
    driver: local