FROM node:14-alpine
LABEL version="1.0"
WORKDIR /home/app
COPY ["package.json","package-lock.json*","npm-shrinkwrap.json*","/home/app/"]
RUN npm install 
COPY . /home/app
EXPOSE 5000
CMD ["npm","run","dev"]